# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_FORUM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_image',
            field=models.ImageField(default='ImageNot.jpg', max_length=1024, upload_to=''),
        ),
    ]
