# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_FORUM', '0002_auto_20151229_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_change_date',
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_image',
            field=models.ImageField(default='ImageNot.jpg', upload_to=''),
        ),
    ]
